# Generated by Django 5.2.7 on 2025-10-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizhistory",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
