# Generated by Django 5.2.7 on 2025-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_quizhistory_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizhistory",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="quizhistory",
            name="last_taken",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
